name: Release Images

on: [ push ]

permissions: write-all

jobs:
    release-image:
        runs-on: ubuntu-latest
        name: Publish Images
        steps:
            -   name: GitHub Registry Login
                uses: docker/login-action@v3
                with:
                    # noinspection SpellCheckingInspection
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Checkout Repository
                uses: actions/checkout@v4
            -   name: Prepare Docker QEMU
                uses: docker/setup-qemu-action@v3
            -   # noinspection SpellCheckingInspection
                name: Prepare Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and Publish Image
                uses: docker/build-push-action@v5
                with:
                    context: php-8.3-fpm
                    platforms: linux/amd64,linux/arm64
                    push: true
                    # noinspection SpellCheckingInspection
                    tags: ghcr.io/datixo/php-8.3-fpm:latest
