name: Release Images

on: [ push ]

permissions: write-all

jobs:
    release-datixo-php-83-fpm:
        runs-on: ubuntu-latest
        name: PHP 8.3
        steps:
            -   name: DockerHub Login
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Checkout Repository
                uses: actions/checkout@v4
            -   name: Prepare Docker QEMU
                uses: docker/setup-qemu-action@v3
            -   # noinspection SpellCheckingInspection
                name: Prepare Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and Publish Image
                uses: docker/build-push-action@v5
                with:
                    context: php-8.3-fpm
                    platforms: linux/amd64,linux/arm64
                    push: true
                    # noinspection SpellCheckingInspection
                    tags: datixo/php-8.3-fpm:latest

    release-datixo-php-83-xdebug-fpm:
        needs: [ release-datixo-php-83-fpm ]
        runs-on: ubuntu-latest
        name: PHP 8.3 + Xdebug
        steps:
            -   name: DockerHub Login
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Checkout Repository
                uses: actions/checkout@v4
            -   name: Prepare Docker QEMU
                uses: docker/setup-qemu-action@v3
            -   # noinspection SpellCheckingInspection
                name: Prepare Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and Publish Image
                uses: docker/build-push-action@v5
                with:
                    context: php-8.3-xdebug-fpm
                    platforms: linux/amd64,linux/arm64
                    push: true
                    # noinspection SpellCheckingInspection
                    tags: datixo/php-8.3-xdebug-fpm:latest
